### ISSUE TITLE
Cannot get it running with 0.65 from github

### ISSUE THREAD

**Issue by svenn71** [Osndok/zim-plugin-append#4]
I am trying out this plugin with zim from github.
I put the plugin into $HOME/.local/share/zim/plugins and run the buy bread example:
zim --plugin append -j -t -l "Went to buy bread."

```
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 741, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 549, in run
    cmd = build_command(args)
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 476, in build_command
    mod = get_module('zim.plugins.' + cmd)
  File "/usr/local/lib/python2.7/dist-packages/zim/utils/__init__.py", line 39, in get_module
    mod = __import__(name)
  File "/home/svennb/.local/share/zim/plugins/append.py", line 47, in <module>
    from zim.command import Command
ImportError: No module named command
```
find that Command is in zim.main.command on the github version so I go ahead and modify append.py line to

    from zim.main.command import Command

then I get the error

```
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 741, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 549, in run
    cmd = build_command(args)
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 476, in build_command
    mod = get_module('zim.plugins.' + cmd)
  File "/usr/local/lib/python2.7/dist-packages/zim/utils/__init__.py", line 39, in get_module
    mod = __import__(name)
  File "/home/svennb/.local/share/zim/plugins/append.py", line 50, in <module>
    from zim.notebook import Notebook, PageNameError, Path, NotebookInfo, \
ImportError: cannot import name PageNameError
```

A blind attempt to get further, I just delete `PageNameError` from the import and get

```
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 741, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 549, in run
    cmd = build_command(args)
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 476, in build_command
    mod = get_module('zim.plugins.' + cmd)
  File "/usr/local/lib/python2.7/dist-packages/zim/utils/__init__.py", line 39, in get_module
    mod = __import__(name)
  File "/home/svennb/.local/share/zim/plugins/append.py", line 52, in <module>
    from zim.ipc import start_server_if_not_running, ServerProxy
ImportError: No module named ipc
```

I find that ipc is in zim/main/ipc.py so I modify the import line to 

    from zim.main.ipc import start_server ...

Then I get the error

```
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 741, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 549, in run
    cmd = build_command(args)
  File "/usr/local/lib/python2.7/dist-packages/zim/main/__init__.py", line 476, in build_command
    mod = get_module('zim.plugins.' + cmd)
  File "/usr/local/lib/python2.7/dist-packages/zim/utils/__init__.py", line 39, in get_module
    mod = __import__(name)
  File "/home/svennb/.local/share/zim/plugins/append.py", line 52, in <module>
    from zim.main.ipc import start_server_if_not_running, ServerProxy
ImportError: cannot import name start_server_if_not_running
```

When I look into zim/main/ipc.py, there is no such thing as `start_server_if_not_running`

Then I realize that I should ask which version of zim was used when writing this plugin as there seems to be some reorg going on in the source code at the moment.

**Comment by Osndok** [comment]
Thanks for the detail, it should help. I noticed that you said "0.65 from github"... by that do you mean the 0.65 tag, or a newer commit?

Also, although I intend to fix this soon, I know that the append plugin currently requires the zim notebook to be open. Did you test it with zim running/open?

**Comment by svenn71** [comment]
Running on master and starting zim with -D and having a notebook open before trying to run the command line append.
